Módulo 03 Lección 1 - 03 Análisis de caso
# La librería NumPy
**Situación inicial** 📍
<br>
Una empresa de análisis financiero está desarrollando una herramienta para el procesamiento de grandes volúmenes de datos sobre el rendimiento de sus activos en la bolsa. Actualmente, su equipo trabaja con datos en formatos dispersos y estructuras poco optimizadas, lo que ralentiza los cálculos y dificulta la obtención de métricas en tiempo real.
El equipo ha decidido implementar NumPy para optimizar la carga, manipulación y análisis de datos, permitiendo realizar operaciones matemáticas y estadísticas de manera eficiente. Sin embargo, necesitan definir una estrategia clara para estructurar los datos, realizar cálculos rápidos y extraer información clave de forma ágil. Tu misión será analizar esta situación y aplicar los conceptos aprendidos de NumPy para mejorar los procesos de manipulación y análisis de datos.<br><br>
**Descripción del Caso** 🔎
<br>
En este caso, asumirás el rol de un analista de datos dentro del equipo de desarrollo de la empresa. Tu objetivo será optimizar la manipulación de datos utilizando NumPy, mejorando la eficiencia de los cálculos financieros y facilitando la toma de decisiones basada en métricas clave.
Deberás trabajar con matrices y arreglos en NumPy para realizar operaciones como:
- Creación y manipulación de arrays multidimensionales.
- Aplicación de funciones estadísticas y matemáticas sobre los datos.
- Indexación y selección eficiente de elementos dentro de los arrays.
- Optimización del rendimiento computacional mediante el uso de broadcasting y operaciones vectorizadas.
A lo largo del análisis, deberás presentar soluciones concretas que permitan mejorar el procesamiento de los datos y justificar por qué NumPy es la herramienta adecuada para esta tarea.
**Instrucciones** 💡
1. Carga y estructuración de datos:
    - Crea un array NumPy con datos financieros simulados (por ejemplo,precios de acciones en diferentes días).
    - Organiza los datos en una matriz de 5x5, donde cada fila representa una acción y cada columna un día de cotización.
2. Análisis y transformación de datos:
    - Obtén el promedio, valor máximo y mínimo de cada acción a lo largo del tiempo.
    - Calcula la variación porcentual diaria de cada acción.
    - Aplica funciones matemáticas como logaritmo, exponencial o normalización sobre los datos.
3. Optimización y selección de datos:
    - Utiliza indexación avanzada para extraer información específica, como el rendimiento de una acción en un día determinado.
    - Aplica broadcasting para realizar operaciones sin necesidad de bucles.
4. Comparación con otros métodos:
    - Analiza cómo se podrían realizar estas tareas sin NumPy y compara la eficiencia en términos de código y rendimiento computacional.<br>

**Entregables** 📬
<br>

Los participantes deberán entregar un informe con:
1. Código fuente en Python con la implementación de las tareas.
2. Explicación detallada de cada paso realizado y su justificación técnica.
3. Análisis comparativo entre el uso de NumPy y otros métodos tradicionales de manipulación de datos.
4. Conclusiones sobre la eficiencia de NumPy en la manipulación y análisis de datos numéricos.

### Carga y estructuración de datos

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(0)  # Para resultados reproducibles
precios = np.random.randint(550000, 1500001, size=(5, 5))
precios

array([[ 855711,  985829,  667952,  702315, 1432371],
       [ 909783,  854137,  672579, 1160581,  998242],
       [ 924564, 1285831, 1286326,  860744,  720584],
       [1389052, 1154474, 1091377, 1499734, 1224343],
       [ 920775, 1295048, 1437633,  805653, 1156745]], dtype=int32)

### Análisis y transformación de datos

**Cálculos promedio, valores máximos y mínimos, variación porcentua, logaritmo natural y normalización Min-Max con funciones de la librería**

In [3]:
print(f"Los promedios de las acciones por días son: {np.mean(precios, axis=1)}")
print(f"Los máximos por días son: {np.max(precios, axis=1)}")
print(f"Los mínimos por días son: {np.min(precios, axis=1)}")

Los promedios de las acciones por días son: [ 928835.6  919064.4 1015609.8 1271796.  1123170.8]
Los máximos por días son: [1432371 1160581 1286326 1499734 1437633]
Los mínimos por días son: [ 667952  672579  720584 1091377  805653]


<br>

**Variación porcentual diaria de cada acción**

In [4]:
# muestra en notación ciéntifica
variacion = (precios[:, 1:] - precios[:, :-1]) / precios[:, :-1] * 100
print(f"Las variaciones porcentuales son: \n{variacion}")

Las variaciones porcentuales son: 
[[ 1.52058347e+01 -3.22446388e+01  5.14453134e+00  1.03949937e+02]
 [-6.11640358e+00 -2.12563090e+01  7.25568298e+01 -1.39877355e+01]
 [ 3.90743096e+01  3.84965054e-02 -3.30850811e+01 -1.62835872e+01]
 [-1.68876327e+01 -5.46543274e+00  3.74166764e+01 -1.83626563e+01]
 [ 4.06476066e+01  1.10100166e+01 -4.39597589e+01  4.35785630e+01]]


In [5]:
# muestra en notación decimal
variacion_redondeada = np.round(variacion, 1)
print(f"Las variaciones porcentuales son: \n{variacion_redondeada}")

Las variaciones porcentuales son: 
[[ 15.2 -32.2   5.1 103.9]
 [ -6.1 -21.3  72.6 -14. ]
 [ 39.1   0.  -33.1 -16.3]
 [-16.9  -5.5  37.4 -18.4]
 [ 40.6  11.  -44.   43.6]]


<br>

**Logaritmo natural**

In [6]:
print(f"Los logaritmos naturales son: \n{np.log(precios)}")

Los logaritmos naturales son: 
[[13.65968798 13.80123819 13.41197159 13.4621373  14.17484167]
 [13.72096139 13.65784688 13.41887486 13.9644313  13.81375101]
 [13.73707755 14.06691576 14.06730065 13.66555241 13.48781727]
 [14.14413206 13.95915539 13.90295076 14.22079832 14.01791493]
 [13.73297099 14.07405832 14.17850857 13.59940841 13.96112058]]


<br>

**Función exponencial**

In [7]:
print(f"Las funciones exponenciales son: \n{np.exp(precios / 1e6)}")

Las funciones exponenciales son: 
[[2.3530468  2.68003271 1.95023914 2.01841995 4.18861864]
 [2.48378349 2.34934602 1.9592838  3.19178717 2.71350729]
 [2.52076897 3.61767299 3.61946419 2.36491954 2.05563335]
 [4.01104578 3.17235432 2.97837247 4.4804971  3.40193028]
 [2.51123584 3.65117123 4.21071724 2.23815754 3.17956692]]


<br>

**Normalización Min-Max**

In [8]:
norm_precios = (precios - precios.min()) / (precios.max() - precios.min())
print(f"Los precios normalizados son: \n{norm_precios}")

Los precios normalizados son: 
[[0.22573102 0.38216384 0.         0.04131251 0.91901364]
 [0.29073844 0.2238387  0.00556276 0.59225735 0.39708722]
 [0.30850872 0.74283767 0.74343277 0.23178189 0.06327619]
 [0.86693388 0.58491528 0.50905766 1.         0.66891445]
 [0.30395344 0.7539187  0.92533981 0.16554939 0.58764556]]


### Optimización y selección de datos
**indexación avanzada**

In [9]:
print(f"El precio de la acción 2 del día 2 es: ${precios[1, 2]:,}".replace(",", "."))

subset = precios[[0, 2]][:, [1, 3]]
df_subset = pd.DataFrame(
    {
        "Nro. Acción": [1, 3],
        "Día 2": subset[:, 0],
        "Día 4": subset[:, 1]
    }
)

# Formato con separador de miles
df_formateado = df_subset.copy()
df_formateado["Día 2"] = df_formateado["Día 2"].apply(lambda x: f"${x:,}".replace(",", "."))
df_formateado["Día 4"] = df_formateado["Día 4"].apply(lambda x: f"${x:,}".replace(",", "."))

print("\nPrecio de acciones:")
df_formateado


El precio de la acción 2 del día 2 es: $672.579

Precio de acciones:


Nro. Acción       Día 2     Día 4
0            1    $985.829  $702.315
1            3  $1.285.831  $860.744

**Broadcasting**

In [10]:
# Aumentar el precio en un 5% con aproximación clásica
precios_aumento_5 = precios * 1.05
precios_aumento_5 = np.round(precios_aumento_5).astype(int)
precios_aumento_5

array([[ 898497, 1035120,  701350,  737431, 1503990],
       [ 955272,  896844,  706208, 1218610, 1048154],
       [ 970792, 1350123, 1350642,  903781,  756613],
       [1458505, 1212198, 1145946, 1574721, 1285560],
       [ 966814, 1359800, 1509515,  845936, 1214582]])

In [11]:
# Consolidar a Dataframe y formatear valores
df_aumento_5 = pd.DataFrame(
    {
        "Nro. Acción": list(range(1, 6)),
        "Día 1": precios_aumento_5[:, 0],
        "Día 2": precios_aumento_5[:, 1],
        "Día 3": precios_aumento_5[:, 2],
        "Día 4": precios_aumento_5[:, 3],
        "Día 5": precios_aumento_5[:, 4]
    }
)
df_aumento_5

Nro. Acción    Día 1    Día 2    Día 3    Día 4    Día 5
0            1   898497  1035120   701350   737431  1503990
1            2   955272   896844   706208  1218610  1048154
2            3   970792  1350123  1350642   903781   756613
3            4  1458505  1212198  1145946  1574721  1285560
4            5   966814  1359800  1509515   845936  1214582

In [12]:
# Dar formota a valores
df_aumento_f = df_aumento_5.copy()
for dia in ["Día 1", "Día 2", "Día 3", "Día 4", "Día 5"]:
    df_aumento_f[dia] = df_aumento_f[dia].apply(lambda x: f"${x:,}".replace(",", "."))

print("Precios de Acciones aumentado en un 5%\n")
df_aumento_f

Precios de Acciones aumentado en un 5%



Nro. Acción       Día 1       Día 2       Día 3       Día 4       Día 5
0            1    $898.497  $1.035.120    $701.350    $737.431  $1.503.990
1            2    $955.272    $896.844    $706.208  $1.218.610  $1.048.154
2            3    $970.792  $1.350.123  $1.350.642    $903.781    $756.613
3            4  $1.458.505  $1.212.198  $1.145.946  $1.574.721  $1.285.560
4            5    $966.814  $1.359.800  $1.509.515    $845.936  $1.214.582

### Comparación con otros métodos (sin NumPy)

**Cálculos promedio, valores máximos y mínimos y Aumentar en 5% el precio de las acciones**

In [13]:
# Calcular promedios
precios_lista = precios.tolist()
promedios_sin_numpy = []

for fila in precios_lista:
    promedio = sum(fila) / len(fila)
    promedios_sin_numpy.append(promedio)
promedios_sin_numpy

[928835.6, 919064.4, 1015609.8, 1271796.0, 1123170.8]

In [14]:
# Convertir matriz NumPy a lista de listas
precios_lista = precios.tolist()

# Valor mínimo
minimo = precios_lista[0][0]
for fila in precios_lista:
    for valor in fila:
        if valor < minimo:
            minimo = valor

# Valor máximo
maximo = precios_lista[0][0]
for fila in precios_lista:
    for valor in fila:
        if valor > maximo:
            maximo = valor
print(f"El valor mínimo es el siguiente: {minimo}")
print(f"El valor máximo es el siguiente: {maximo}")

El valor mínimo es el siguiente: 667952
El valor máximo es el siguiente: 1499734


In [15]:
# Aumentar los precios en un 5%
precios_aumento_sin_numpy = []

for fila in precios_lista:
    nueva_fila = [x * 1.05 for x in fila]
    precios_aumento_sin_numpy.append(nueva_fila)
precios_aumento_sin_numpy

[[898496.55, 1035120.4500000001, 701349.6, 737430.75, 1503989.55],
 [955272.15,
  896843.8500000001,
  706207.9500000001,
  1218610.05,
  1048154.1000000001],
 [970792.2000000001,
  1350122.55,
  1350642.3,
  903781.2000000001,
  756613.2000000001],
 [1458504.6, 1212197.7, 1145945.85, 1574720.7, 1285560.1500000001],
 [966813.75, 1359800.4000000001, 1509514.6500000001, 845935.65, 1214582.25]]

<br>

### Explicación


**Fórmula de Variación:**

Para calcular la variación se usa la siguiente formula.

$$
\text{variación} = \left( \frac{\text{precio}_{\text{día actual}} - \text{precio}_{\text{día anterior}}}{\text{precio}_{\text{día anterior}}} \right) \times 100
$$

**Normalización Min-Max:**

Transforma los valores numéricos para que estén en el rango entre 0 y 1, manteniendo la proporción relativa entre ellos, es una técnica fundamental en análisis de datos y Machine Learning.

**Indexación Avanzada:**

Permite acceder, extraer o modificar subconjuntos de datos en arreglos utilizando listas o arrays de índices, en lugar de usar solo rangos simples.

**Broadcasting:**

Es la capacidad de NumPy para aplicar operaciones entre arrays de diferentes formas (shapes) automáticamente, extendiendo los valores más pequeños sin necesidad de algún iterador

**Comparar con otros métodos distintos a NumPy**

NumPy permite realizar tareas complejas de forma mucho más eficiente, legible y escalable que usando estructuras básicas de Python.
Cuando se trabaja con grandes volúmenes de datos numéricos, NumPy reduce el tiempo de cómputo y la complejidad del código.