Módulo 03 Lección 1 - 02 Ejercicios de aplicación

# La Librería NumPy

1. Desafío 🎯
   Este desafío consiste en la creación y manipulación de arrays y matrices en NumPy, así como la aplicación de operaciones matemáticas y algebraicas avanzadas.
    - Creación y manipulación de arrays:
        - Genera un array unidimensional de 20 números enteros aleatorios entre 1 y 100.
        - Calcula la suma, promedio, máximo y mínimo del array.
        - Ordena el array en forma ascendente y descendente.
        - Extrae todos los valores pares del array.
        - Reemplaza todos los valores impares por -1.
    - Operaciones con matrices:
        - Crea dos matrices (4x4) de números enteros aleatorios entre 1 y 50.
        - Realiza la suma, resta y multiplicación matricial entre ambas matrices.
        - Calcula la matriz transpuesta de la primera matriz.
        - Obtén el determinante de la segunda matriz.
        - Encuentra la inversa de la segunda matriz (si es invertible).
    - Aplicación de funciones en NumPy:
        - Genera un array de 100 valores distribuidos uniformemente entre 0 y 10.
        - Calcula la seno y coseno de cada valor en el array.
        - Aplica la función exponencial a cada elemento del array.
        - Encuentra la raíz cuadrada de cada elemento mayor a 5 en el array.
2. Recursos🛠️<br>
    Documentación de NumPy: https://numpy.org/doc/
3. Plus ➕
    - Escribe funciones que realicen cada operación de manera modular.
    - Prueba con diferentes tamaños de matrices y analiza cómo cambian los resultados.
    - Experimenta aplicando NumPy a conjuntos de datos reales
4. ⚠️Condición <br>
   Esta práctica o ejercitación no requiere ser entregada y/o evaluada por el mentor. No obstante puedes compartir tus resultados con el resto de los bootcampers y construir conocimiento en conjunto.


In [1]:
import numpy as np

<br>

### Creación y manipulación de arrays

In [2]:
# Array unidimensional de 20 números aleatorios entre 1 y 100
arr_num = np.random.randint(1, 101, 20)
divisor = "-----------------------------"
print(f"{divisor}\nArray de 20 números aleatorios entre 1 y 100: {arr_num}")
print(f"{divisor}\nSuma: {np.sum(arr_num)}")
print(f"{divisor}\nPromedio: {np.mean(arr_num)}")
print(f"{divisor}\nMáximo: {np.max(arr_num)}")
print(f"{divisor}\nMínimo: {np.min(arr_num)}")
print(f"{divisor}\nOrden ascendente: {np.sort(arr_num)}")
print(f"{divisor}\nOrden descendente: {-np.sort(-arr_num)}")
print(f"{divisor}\nValores pares: {arr_num[arr_num % 2 == 0]}")

arr_impares = np.where(arr_num % 2 != 0, -1, arr_num)
print(f"{divisor}\nArray con impares reemplazados por -1: {arr_impares}")


-----------------------------
Array de 20 números aleatorios entre 1 y 100: [21 70 83 68 16  5 82  1 56 14 92 90 26 87 93 20 95 95 19 66]
-----------------------------
Suma: 1099
-----------------------------
Promedio: 54.95
-----------------------------
Máximo: 95
-----------------------------
Mínimo: 1
-----------------------------
Orden ascendente: [ 1  5 14 16 19 20 21 26 56 66 68 70 82 83 87 90 92 93 95 95]
-----------------------------
Orden descendente: [95 95 93 92 90 87 83 82 70 68 66 56 26 21 20 19 16 14  5  1]
-----------------------------
Valores pares: [70 68 16 82 56 14 92 90 26 20 66]
-----------------------------
Array con impares reemplazados por -1: [-1 70 -1 68 16 -1 82 -1 56 14 92 90 26 -1 -1 20 -1 -1 -1 66]


<br>

### Operaciones con matrices

In [3]:
# Matrices 4x4 con enteros entre 1 y 50
mat1 = np.random.randint(1, 51, size=(4, 4))
mat2 = np.random.randint(1, 51, size=(4, 4))

print("Matriz 1:\n", mat1)
print("Matriz 2:\n", mat2)

print(f"Suma de matrices :\n {mat1 + mat2}")
print(f"Resta de matrices:\n {mat1 - mat2}")
print(f"Multiplicación matricial:\n", np.dot(mat1, mat2))  # o mat1 @ mat2
print(f"Transpuesta de la Matriz 1:\n", mat1.T)
print(f"Determinante de la Matriz 2:", np.linalg.det(mat2))

# Intentar invertir la matriz 2
try:
    inversa = np.linalg.inv(mat2)
    print("Inversa de la Matriz 2:\n", inversa)
except np.linalg.LinAlgError:
    print("La matriz 2 no es invertible.")

Matriz 1:
 [[19 19  1 35]
 [42 26 16  8]
 [ 2 41 15  1]
 [50 22 44 34]]
Matriz 2:
 [[42 40 17 15]
 [28  4 50 35]
 [ 8 12 40  6]
 [ 1 17 20  5]]
Suma de matrices :
 [[61 59 18 50]
 [70 30 66 43]
 [10 53 55  7]
 [51 39 64 39]]
Resta de matrices:
 [[-23 -21 -16  20]
 [ 14  22 -34 -27]
 [ -6  29 -25  -5]
 [ 49   5  24  29]]
Multiplicación matricial:
 [[1373 1443 2013 1131]
 [2628 2112 2814 1676]
 [1353  441 2704 1560]
 [3102 3194 4390 1954]]
Transpuesta de la Matriz 1:
 [[19 42  2 50]
 [19 26 41 22]
 [ 1 16 15 44]
 [35  8  1 34]]
Determinante de la Matriz 2: -584283.9999999991
Inversa de la Matriz 2:
 [[ 0.02221522 -0.00459708  0.03384484 -0.07507993]
 [ 0.00811249 -0.00784208 -0.02230936  0.05732829]
 [-0.00518241 -0.00216333  0.03640353 -0.01299368]
 [-0.01129588  0.0362358  -0.07653128  0.07207454]]


<br>

### Aplicación de funciones en NumPy

In [4]:
# Generar un array de 100 valores uniformemente distribuidos entre 0 y 10
valores = np.linspace(0, 10, 100)
valores

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [5]:
# Calcula el seno de cada valor
seno_valores = np.sin(valores)
seno_valores

array([ 0.        ,  0.10083842,  0.20064886,  0.2984138 ,  0.39313661,
        0.48385164,  0.56963411,  0.64960951,  0.72296256,  0.78894546,
        0.84688556,  0.8961922 ,  0.93636273,  0.96698762,  0.98775469,
        0.99845223,  0.99897117,  0.98930624,  0.96955595,  0.93992165,
        0.90070545,  0.85230712,  0.79522006,  0.73002623,  0.65739025,
        0.57805259,  0.49282204,  0.40256749,  0.30820902,  0.21070855,
        0.11106004,  0.01027934, -0.09060615, -0.19056796, -0.28858706,
       -0.38366419, -0.47483011, -0.56115544, -0.64176014, -0.7158225 ,
       -0.7825875 , -0.84137452, -0.89158426, -0.93270486, -0.96431712,
       -0.98609877, -0.99782778, -0.99938456, -0.99075324, -0.97202182,
       -0.94338126, -0.90512352, -0.85763861, -0.80141062, -0.73701276,
       -0.66510151, -0.58640998, -0.50174037, -0.41195583, -0.31797166,
       -0.22074597, -0.12126992, -0.0205576 ,  0.0803643 ,  0.18046693,
        0.27872982,  0.37415123,  0.46575841,  0.55261747,  0.63

In [6]:
# Calcula el coseno de cada valor
coseno_valores = np.cos(valores)
coseno_valores

array([ 1.        ,  0.99490282,  0.97966323,  0.95443659,  0.91948007,
        0.87515004,  0.8218984 ,  0.76026803,  0.69088721,  0.61446323,
        0.53177518,  0.44366602,  0.35103397,  0.25482335,  0.15601496,
        0.0556161 , -0.04534973, -0.14585325, -0.24486989, -0.34139023,
       -0.43443032, -0.52304166, -0.60632092, -0.68341913, -0.75355031,
       -0.81599952, -0.87013012, -0.91539031, -0.95131866, -0.97754893,
       -0.9938137 , -0.99994717, -0.9958868 , -0.981674  , -0.95745366,
       -0.92347268, -0.88007748, -0.82771044, -0.76690542, -0.69828229,
       -0.6225406 , -0.54045251, -0.45285485, -0.36064061, -0.26474988,
       -0.16616018, -0.06587659,  0.03507857,  0.13567613,  0.23489055,
        0.33171042,  0.4251487 ,  0.51425287,  0.59811455,  0.67587883,
        0.74675295,  0.8100144 ,  0.86501827,  0.91120382,  0.94810022,
        0.97533134,  0.99261957,  0.99978867,  0.99676556,  0.98358105,
        0.96036956,  0.9273677 ,  0.88491192,  0.83343502,  0.77

In [7]:
# Aplicar la función exponencial a cada elemento
exponencial_valores = np.exp(valores)
exponencial_valores

array([1.00000000e+00, 1.10628782e+00, 1.22387273e+00, 1.35395549e+00,
       1.49786447e+00, 1.65706921e+00, 1.83319548e+00, 2.02804182e+00,
       2.24359796e+00, 2.48206508e+00, 2.74587836e+00, 3.03773178e+00,
       3.36060565e+00, 3.71779709e+00, 4.11295363e+00, 4.55011049e+00,
       5.03373179e+00, 5.56875615e+00, 6.16064708e+00, 6.81544881e+00,
       7.53984798e+00, 8.34124196e+00, 9.22781435e+00, 1.02086186e+01,
       1.12936704e+01, 1.24940499e+01, 1.38220152e+01, 1.52911270e+01,
       1.69163875e+01, 1.87143934e+01, 2.07035054e+01, 2.29040358e+01,
       2.53384558e+01, 2.80316249e+01, 3.10110451e+01, 3.43071414e+01,
       3.79535725e+01, 4.19875748e+01, 4.64503425e+01, 5.13874480e+01,
       5.68493076e+01, 6.28916963e+01, 6.95763174e+01, 7.69714323e+01,
       8.51525577e+01, 9.42032371e+01, 1.04215893e+02, 1.15292773e+02,
       1.27546990e+02, 1.41103681e+02, 1.56101284e+02, 1.72692948e+02,
       1.91048105e+02, 2.11354190e+02, 2.33818566e+02, 2.58670631e+02,
      

In [8]:
# Filtrar los valores mayores a 5
mayores_5 = valores[valores > 5]

# Calcular la raíz cuadrada solo de esos valores
raices_cuadradas = np.sqrt(mayores_5)

print("Valores mayores a 5:\n", mayores_5)
print("Raíces cuadradas:\n", raices_cuadradas)

Valores mayores a 5:
 [ 5.05050505  5.15151515  5.25252525  5.35353535  5.45454545  5.55555556
  5.65656566  5.75757576  5.85858586  5.95959596  6.06060606  6.16161616
  6.26262626  6.36363636  6.46464646  6.56565657  6.66666667  6.76767677
  6.86868687  6.96969697  7.07070707  7.17171717  7.27272727  7.37373737
  7.47474747  7.57575758  7.67676768  7.77777778  7.87878788  7.97979798
  8.08080808  8.18181818  8.28282828  8.38383838  8.48484848  8.58585859
  8.68686869  8.78787879  8.88888889  8.98989899  9.09090909  9.19191919
  9.29292929  9.39393939  9.49494949  9.5959596   9.6969697   9.7979798
  9.8989899  10.        ]
Raíces cuadradas:
 [2.24733287 2.26969495 2.29183884 2.31377081 2.33549683 2.3570226
 2.37835356 2.3994949  2.42045158 2.44122837 2.46182982 2.48226029
 2.50252398 2.5226249  2.5425669  2.56235372 2.5819889  2.60147588
 2.62081798 2.64001837 2.65908012 2.67800619 2.69679945 2.71546264
 2.73399844 2.75240941 2.77069805 2.78886676 2.80691786 2.82485362
 2.84267622 2.86

<br>

## Explicaciones

**Sean dos matrices 4x4:**

$\text{Matriz\ 1} =
\begin{bmatrix}
a_{11} & a_{12} & a_{13} & a_{14} \\
a_{21} & a_{22} & a_{23} & a_{24} \\
a_{31} & a_{32} & a_{33} & a_{34} \\
a_{41} & a_{42} & a_{43} & a_{44}
\end{bmatrix}
\quad y
\quad
\text{Matriz\ 2} =
\begin{bmatrix}
b_{11} & b_{12} & b_{13} & b_{14} \\
b_{21} & b_{22} & b_{23} & b_{24} \\
b_{31} & b_{32} & b_{33} & b_{34} \\
b_{41} & b_{42} & b_{43} & b_{44}
\end{bmatrix}
$

<br>

**Multiplicación de Matrices:**

<br>

$\text{Matriz\ Resultante} = \text{Matriz\ 1} \cdot \text{Matriz\ 2}$:


**Fila 1:**

$r_{11} = a_{11} \times b_{11} + a_{12} \cdot b_{21} + a_{13} \cdot b_{31} + a_{14} \cdot b_{41}$  
$r_{12} = a_{11} \cdot b_{12} + a_{12} \cdot b_{22} + a_{13} \cdot b_{32} + a_{14} \cdot b_{42}$  
$r_{13} = a_{11} \cdot b_{13} + a_{12} \cdot b_{23} + a_{13} \cdot b_{33} + a_{14} \cdot b_{43}$  
$r_{14} = a_{11} \cdot b_{14} + a_{12} \cdot b_{24} + a_{13} \cdot b_{34} + a_{14} \cdot b_{44}$  

**Fila 2:**

$r_{21} = a_{21} \cdot b_{11} + a_{22} \cdot b_{21} + a_{23} \cdot b_{31} + a_{24} \cdot b_{41}$  
$r_{22} = a_{21} \cdot b_{12} + a_{22} \cdot b_{22} + a_{23} \cdot b_{32} + a_{24} \cdot b_{42}$  
$r_{23} = a_{21} \cdot b_{13} + a_{22} \cdot b_{23} + a_{23} \cdot b_{33} + a_{24} \cdot b_{43}$  
$r_{24} = a_{21} \cdot b_{14} + a_{22} \cdot b_{24} + a_{23} \cdot b_{34} + a_{24} \cdot b_{44}$  

**Fila 3:**

$r_{31} = a_{31} \cdot b_{11} + a_{32} \cdot b_{21} + a_{33} \cdot b_{31} + a_{34} \cdot b_{41}$  
$r_{32} = a_{31} \cdot b_{12} + a_{32} \cdot b_{22} + a_{33} \cdot b_{32} + a_{34} \cdot b_{42}$  
$r_{33} = a_{31} \cdot b_{13} + a_{32} \cdot b_{23} + a_{33} \cdot b_{33} + a_{34} \cdot b_{43}$  
$r_{34} = a_{31} \cdot b_{14} + a_{32} \cdot b_{24} + a_{33} \cdot b_{34} + a_{34} \cdot b_{44}$  

**Fila 4:**

$r_{41} = a_{41} \cdot b_{11} + a_{42} \cdot b_{21} + a_{43} \cdot b_{31} + a_{44} \cdot b_{41}$  
$r_{42} = a_{41} \cdot b_{12} + a_{42} \cdot b_{22} + a_{43} \cdot b_{32} + a_{44} \cdot b_{42}$  
$r_{43} = a_{41} \cdot b_{13} + a_{42} \cdot b_{23} + a_{43} \cdot b_{33} + a_{44} \cdot b_{43}$  
$r_{44} = a_{41} \cdot b_{14} + a_{42} \cdot b_{24} + a_{43} \cdot b_{34} + a_{44} \cdot b_{44}$  

<br>

$\text{Matriz\ Resultante} = \begin{bmatrix}
r_{11} & r_{12} & r_{13} & r_{14} \\
r_{21} & r_{22} & r_{23} & r_{24} \\
r_{31} & r_{32} & r_{33} & r_{34} \\
r_{41} & r_{42} & r_{43} & r_{44}
\end{bmatrix}$

<br>

**Traspuesta de Matriz 1:**

La traspuesta de una matriz se obtiene al intercambiar filas por columnas**. Es decir, el elemento en la posición \((i, j)\) pasa a la posición \((j, i)\).


$\text{Matriz\ 1} =
\begin{bmatrix}
a_{11} & a_{12} & a_{13} & a_{14} \\
a_{21} & a_{22} & a_{23} & a_{24} \\
a_{31} & a_{32} & a_{33} & a_{34} \\
a_{41} & a_{42} & a_{43} & a_{44}
\end{bmatrix}
\quad \text{Matriz\ 1}^{\mathrm{T}} =
\begin{bmatrix}
a_{11} & a_{21} & a_{31} & a_{41} \\
a_{12} & a_{22} & a_{32} & a_{42} \\
a_{13} & a_{23} & a_{33} & a_{43} \\
a_{14} & a_{24} & a_{34} & a_{44}
\end{bmatrix}$

<br>

**Determinante de Matriz 2:**

Se usa la regla de Laplace, que consiste en expandir el determinante por una fila o columna (usualmente la primera) y calcular determinantes de matrices 3×3 (menores), multiplicados por sus respectivos cofactores, es decir, requiere calcular cuatro determinantes de matrices 3×3, multiplicarlos por sus cofactores (los elementos de la fila o columna elegida), y luego combinarlos con signos alternados.

<br>

Matriz 2:    
|     |     |     |     |
|-----|-----|-----|-----|
| b11 | b12 | b13 | b14 |
| b21 | b22 | b23 | b24 |
| b31 | b32 | b33 | b34 |
| b41 | b42 | b43 | b44 |

Sub-Matriz b11 (M11), elimina fila 1 y columna 1

|     |     |     |
|-----|-----|-----|
| b22 | b23 | b24 |
| b32 | b33 | b34 |
| b42 | b43 | b44 |


$\text{Cálculo\ det(M11)} =$  
$+\, b22 \cdot b33 \cdot b44$  
$+\, b23 \cdot b34 \cdot b42$  
$+\, b24 \cdot b32 \cdot b43$  
$-\, b24 \cdot b33 \cdot b42$  
$-\, b23 \cdot b32 \cdot b44$  
$-\, b22 \cdot b34 \cdot b43$

<br>

Sub-Matriz b12 (M12), elimina fila 1 y columna 2

|     |     |     |
|-----|-----|-----|
| b21 | b23 | b24 |
| b31 | b33 | b34 |
| b41 | b43 | b44 |

$\text{Cálculo\ det(M12)} =$  
$+\, b21 \cdot b33 \cdot b44$  
$+\, b23 \cdot b34 \cdot b41$  
$+\, b24 \cdot b31 \cdot b43$  
$-\, b24 \cdot b33 \cdot b41$  
$-\, b23 \cdot b31 \cdot b44$  
$-\, b21 \cdot b34 \cdot b43$

<br>

Sub-Matriz b13 (M13), elimina fila 1 y columna 3

|     |     |     |
|-----|-----|-----|
| b21 | b22 | b24 |
| b31 | b32 | b34 |
| b41 | b42 | b44 |

$\text{Cálculo\ det(M13)} =$  
$+\, b21 \cdot b32 \cdot b44$  
$+\, b22 \cdot b34 \cdot b41$  
$+\, b24 \cdot b31 \cdot b42$  
$-\, b24 \cdot b32 \cdot b41$  
$-\, b22 \cdot b31 \cdot b44$  
$-\, b21 \cdot b34 \cdot b42$

<br>

Sub-Matriz b14 (M14), elimina fila 1 y columna 4

|     |     |     |
|-----|-----|-----|
| b21 | b22 | b23 |
| b31 | b32 | b33 |
| b41 | b42 | b43 |

$\text{Cálculo\ det(M14)} =$  
$+\, b21 \cdot b32 \cdot b43$  
$+\, b22 \cdot b33 \cdot b41$  
$+\, b23 \cdot b31 \cdot b42$  
$-\, b23 \cdot b32 \cdot b41$  
$-\, b22 \cdot b31 \cdot b43$  
$-\, b21 \cdot b33 \cdot b42$

<br>

$\text{Det(Matriz 2)} =$
$+\, b_{11} \cdot \text{det(M11)}$
$-\, b_{12} \cdot \text{det(M12)}$
$+\, b_{13} \cdot \text{det(M13)}$
$-\, b_{14} \cdot \text{det(M14)}$




<br>

**Inversa de Matriz 2:**

Para que una matriz cuadrada sea invertible, su determinante debe ser distinto de cero.
La fórmula general de la inversa es:


$\text{Matriz\ 2}^{-1} = \frac{1}{\det(\text{Matriz\ 2})} \cdot \text{adj}(\text{Matriz\ 2})$


Donde:

- $det(\text{Matriz})$ es el determinante
- $\text{adj}(\text{Matriz})$ es la matriz adjunta, es decir, la traspuesta de la matriz de cofactores

<br>

**Matriz 2:**

|     |     |     |     |
|-----|-----|-----|-----|
| b11 | b12 | b13 | b14 |
| b21 | b22 | b23 | b24 |
| b31 | b32 | b33 | b34 |
| b41 | b42 | b43 | b44 |


<br>

**Adjunta de Matriz 2:**

La **adjunta** de una matriz cuadrada se obtiene como la **traspuesta de su matriz de cofactores**.

Cada cofactor \( C_{ij} \) se calcula como:

$C_{ij} = (-1)^{i+j} \cdot \det(M_{ij})$

donde:

- \( M_{ij} \) es el menor de \( b_{ij} \): la submatriz que se forma eliminando la fila \( i \) y la columna \( j \) de la matriz original.
- \( (-1)^{i+j} \) aplica el signo alternado.

<br>

**Explicación práctica:** 
A base de la explicación anterior Determinante de la matriz, los cálculos se calculan a las Sub-Matrices de b11, b12, b13 y b14

<br>

**Matriz 2:**

|     |     |     |     |
|-----|-----|-----|-----|
| b11 | b12 | b13 | b14 |
| b21 | b22 | b23 | b24 |
| b31 | b32 | b33 | b34 |
| b41 | b42 | b43 | b44 |

<br>

$\text{adj}(\text{Matriz 2}) =
\begin{bmatrix}
\phantom{-}\det(M_{11}) & -\det(M_{21}) & \phantom{-}\det(M_{31}) & -\det(M_{41}) \\
-\det(M_{12}) & \phantom{-}\det(M_{22}) & -\det(M_{32}) & \phantom{-}\det(M_{42}) \\
\phantom{-}\det(M_{13}) & -\det(M_{23}) & \phantom{-}\det(M_{33}) & -\det(M_{43}) \\
-\det(M_{14}) & \phantom{-}\det(M_{24}) & -\det(M_{34}) & \phantom{-}\det(M_{44})
\end{bmatrix}$

